# Generated by Django 2.2.6 on 2019-10-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resolved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=10)),
                ('spectype', models.CharField(max_length=10)),
                ('Rband', models.CharField(max_length=10)),
                ('distance', models.CharField(max_length=10)),
                ('diskmajoraxis', models.CharField(max_length=10)),
                ('diskdiameter', models.CharField(max_length=10)),
                ('inclination', models.CharField(max_length=10)),
            ],
        ),
    ]
