# Generated by Django 2.2.6 on 2019-10-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=100, verbose_name='object')),
                ('category', models.CharField(max_length=100, verbose_name='category')),
                ('r_band', models.CharField(max_length=10, verbose_name='r_band')),
                ('distance', models.CharField(max_length=10, verbose_name='distance')),
                ('disk_major_axis', models.CharField(max_length=10, verbose_name='disk_major_axis')),
                ('disk_diameter', models.CharField(max_length=10, verbose_name='disk_diameter')),
                ('inclination', models.CharField(max_length=10, verbose_name='inclination')),
                ('resolution_elements_across', models.CharField(max_length=10, verbose_name='resolution_elements_across')),
                ('at_ref_wavelength', models.CharField(max_length=10, verbose_name='at_ref_wavelength')),
                ('catalog', models.CharField(choices=[('Resolved', 'Resolved'), ('Unresolved', 'Unresolved')], max_length=20, verbose_name='catalog')),
            ],
            options={
                'verbose_name': 'disk',
                'verbose_name_plural': 'disks',
                'ordering': ('object',),
            },
        ),
    ]
