# Generated by Django 2.2.6 on 2019-11-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('ra', models.CharField(blank=True, max_length=100, null=True)),
                ('dec', models.CharField(blank=True, max_length=100, null=True)),
                ('distance', models.CharField(blank=True, max_length=100, null=True)),
                ('system_age', models.CharField(blank=True, max_length=100, null=True)),
                ('stellar_mass', models.CharField(blank=True, max_length=100, null=True)),
                ('disk_major_axis', models.CharField(blank=True, max_length=100, null=True)),
                ('inclination', models.CharField(blank=True, max_length=100, null=True)),
                ('references', models.CharField(blank=True, max_length=1000, null=True)),
                ('catalog', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'disk',
                'verbose_name_plural': 'disks',
                'ordering': ('object',),
            },
        ),
    ]
